sudo: required
language: generic
services:
  - dockerfile

before_install:
  - docker build -t retrofire/docker-react -f Dockerfile.dev .

script:
  - docker run retrofire/docker-react -e CI=true npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-272137328470"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY